VAULT_ADDR: http://130.104.229.14:30000
ingress:
  tls: []
  hosts:
  - paths: []
    host: chart-example.local
  enabled: false
  annotations: {}
securityContext: {}
replicaWorkersCount: 1
service:
  type: ClusterIP
  port: 80
image:
  pullPolicy: Always
  tag: b2c2
  repository: ayhamkassab/caliper
args:
  second: manager
  first: launch
serviceAccount:
  create: true
  name: 
fullnameOverride: 
podSecurityContext: {}
nodeSelector: {}
tolerations: []
ENDORSING_ORG_NAMES: "carrier manufacturer"
nameOverride: 
VAULT_TOKEN: s.5KkfEk3Upun8A1fQr1PfjRWL
replicaMasterCount: 1
affinity: {}
resources: {}
imagePullSecrets: []
